language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: qIJ4OtJcxJmhHa0tY9XparOVRK8BHFfaUkAEHU0rLeKJh831cKiKobOFcBDifomnoH/Cx9M6AW/KLtB36gDXf5R7yRDTUZteZauChmXfE3zfHl2oN8lm4OWoqsCnVLiVWUizwcOdNOqsRoS41tPh9s6OyvDBLkvOt4mB7yKlyJj/02fdV1ysOHQ50M02edwueMjiyHVK3Yqr5nFTJceFRk5YZIWLR19W+TgJhGSNv2Szv0OUkwPKMJv2ra34ovXsVjjIz1WH1Q5CVYI4LH0Lmf37JZgBbqW195klO6mYVkmol4IGIqfAdBhZAIhXxjpEp5MiGhaRI+Kzp/MmXNU+7CNAcIKJe8IS/5urjCXB/otFrAqzZoiyW7uGDvMLNoBwCa7qZvRaqb/TAGXwStfIBnrPbQQQeJT/YAfuNGEwDM4IxqgmS/mUrqw0y3oKeOUT13yj1ksfFz80qY0SE7/Lr0K/pzwsO9gvOcvrhd1kbnupr1WLcKr4lIXL7/YlqB753HPP0MXxtNIQmLJ6HLABA4sXJke1ZyhRWaK2NIN9MWNJhqko1rMu2lKgTxGUYTQMgZXf1qXvAdJaoHluOOJ9gvVojTR6Aedm3ph9vXrfbuwUrKZvgwawF9v7JpT2wNdPskk2ZuTP+c11bb3pykzZ/IgIxGUSioxqH9RgT9e6Lug=
  app: shrouded-fortress-10155
